
export const limits: { [key: number]: any } = {
    4: [{ chainId: 4, isEnabled: true }, { chainId: 5, isEnabled: true }, { chainId: 80001, isEnabled: true }],
    5: [{ chainId: 5, isEnabled: true }, { chainId: 4, isEnabled: true }, { chainId: 80001, isEnabled: true }],
    80001: [{ chainId: 80001, isEnabled: true }, { chainId: 4, isEnabled: true }],
    137: [{
        chainId: 43114,
        isEnabled: true
    }, {
        chainId: 56,
        isEnabled: true
    }, {
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 250,
        isEnabled: true
    }, {
        chainId: 42161,
        isEnabled: true
    }, {
        chainId: 100,
        isEnabled: true
    }, {
        chainId: 1313161554,
        isEnabled: true
    }, {
        chainId: 10,
        isEnabled: true
    }],
    250: [{
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 56,
        isEnabled: true
    }, {
        chainId: 42161,
        isEnabled: true
    }, {
        chainId: 250,
        isEnabled: true
    }, {
        chainId: 43114,
        isEnabled: true
    }, {
        chainId: 100,
        isEnabled: true
    }, {
        chainId: 1313161554,
        isEnabled: true
    }, {
        chainId: 10,
        isEnabled: true
    }],
    56: [{
        chainId: 43114,
        isEnabled: true
    }, {
        chainId: 56,
        isEnabled: true
    }, {
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 250,
        isEnabled: true
    }, {
        chainId: 42161,
        isEnabled: true
    }, {
        chainId: 100,
        isEnabled: true
    }, {
        chainId: 1313161554,
        isEnabled: true
    }, {
        chainId: 10,
        isEnabled: true
    }],
    43114: [{
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 250,
        isEnabled: true
    }, {
        chainId: 56,
        isEnabled: true
    }, {
        chainId: 100,
        isEnabled: true
    }, {
        chainId: 42161,
        isEnabled: true
    }, {
        chainId: 10,
        isEnabled: true
    }, {
        chainId: 43114,
        isEnabled: true
    }, {
        chainId: 1313161554,
        isEnabled: true
    }],
    42161: [{
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 250,
        isEnabled: true
    }, {
        chainId: 56,
        isEnabled: true
    }, {
        chainId: 42161,
        isEnabled: true
    }, {
        chainId: 100,
        isEnabled: true
    }, {
        chainId: 43114,
        isEnabled: true
    }, {
        chainId: 1313161554,
        isEnabled: true
    }, {
        chainId: 10,
        isEnabled: true
    }],
    10: [{
        chainId: 137,
        isEnabled: true,
    }, {
        chainId: 250,
        isEnabled: true,
    }, {
        chainId: 56,
        isEnabled: true,
    }, {
        chainId: 100,
        isEnabled: true,
    }, {
        chainId: 43114,
        isEnabled: true,
    }, {
        chainId: 42161,
        isEnabled: true,
    }, {
        chainId: 10,
        isEnabled: true
    }, {
        chainId: 1313161554,
        isEnabled: true
    }],
    100: [{
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 250,
        isEnabled: true,
    }, {
        chainId: 56,
        isEnabled: true,
    }, {
        chainId: 43114,
        isEnabled: true,
    }, {
        chainId: 42161,
        isEnabled: true,
    }, {
        chainId: 10,
        isEnabled: true,
    }, {
        chainId: 100,
        isEnabled: true,
    }, {
        chainId: 1313161554,
        isEnabled: true
    }],
    31337: [{ chainId: 31337, isEnabled: true, minAmount: '50000000000000000', maxAmount: '10000000000000000000' }],
    1313161554: [{
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 250,
        isEnabled: true,
    }, {
        chainId: 56,
        isEnabled: true,
    }, {
        chainId: 43114,
        isEnabled: true,
    }, {
        chainId: 42161,
        isEnabled: true,
    }, {
        chainId: 10,
        isEnabled: true,
    }, {
        chainId: 100,
        isEnabled: true,
    }, {
        chainId: 1313161554,
        isEnabled: true
    }],
    8453: [{
        chainId: 43114,
        isEnabled: true
    }, {
        chainId: 56,
        isEnabled: true
    }, {
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 42161,
        isEnabled: true
    }, {
        chainId: 100,
        isEnabled: true
    }, {
        chainId: 1313161554,
        isEnabled: true
    }, {
        chainId: 10,
        isEnabled: true
    }, {
        chainId: 324,
        isEnabled: true
    }, {
        chainId: 1101,
        isEnabled: true
    }],
    5000: [{
        chainId: 43114,
        isEnabled: true
    }, {
        chainId: 56,
        isEnabled: true
    }, {
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 42161,
        isEnabled: true
    }, {
        chainId: 100,
        isEnabled: true
    }, {
        chainId: 1313161554,
        isEnabled: true
    }, {
        chainId: 10,
        isEnabled: true
    }, {
        chainId: 324,
        isEnabled: true
    }, {
        chainId: 1101,
        isEnabled: true
    }, {
        chainId: 8453,
        isEnabled: true
        }],
    59144: [{
        chainId: 43114,
        isEnabled: true
    }, {
        chainId: 56,
        isEnabled: true
    }, {
        chainId: 137,
        isEnabled: true
    }, {
        chainId: 42161,
        isEnabled: true
    }, {
        chainId: 100,
        isEnabled: true
    }, {
        chainId: 1313161554,
        isEnabled: true
    }, {
        chainId: 10,
        isEnabled: true
    }, {
        chainId: 324,
        isEnabled: true
    }, {
        chainId: 1101,
        isEnabled: true
    }, {
        chainId: 8453,
        isEnabled: true
    },
      {
        chainId: 5000,
        isEnabled: true
    }]
}
